<a href="https://colab.research.google.com/github/GloriousMir/ARTIFICIAL-INTELLIGENCE-AND-EXPERT-SYSTEM/blob/main/Week_07_N_Puzzle_Solvability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [5]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [6]:
get_state(3)

[[3 8 2]
 [5 1 4]
 [0 6 7]]


[3, 8, 2, 5, 1, 4, 0, 6, 7]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [7]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [8]:
s = get_state(4)
count_inversion(s)

[[14 13  2  8]
 [12  1  5  6]
 [10  4 11  0]
 [ 9  3  7 15]]
[14, 13, 2, 8, 12, 1, 5, 6, 10, 4, 11, 0, 9, 3, 7, 15]


66

# **Find blank row**

In [24]:
# find row position of the blank tile
def get_blank_row(state):


SyntaxError: ignored

# Solvability Rules

In [34]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def getInvCount(arr):
	inv_count = 0
	empty_value = -1
	for i in range(0, 9):
		for j in range(i + 1, 9):
			if arr[j] != empty_value and arr[i] != empty_value and arr[i] > arr[j]:
				inv_count += 1
	return inv_count

	
import math
def isSolvable(initialState):
    N = math.sqrt(len(initialState))
    I = count_inversion(initialState)
    R = int(np.ceil(N - initialState.index(0)/N))
    print(N)
    print(R)
    print(I)
    # decide solvability
    if N%2 != 0 and I%2 == 0:
        print("Solvable")

    elif N%2==0 and R%2!=0 and I%2 == 0:
        print("Solvable")

    elif N%2==0 and R%2==0 and I%2 != 0:
        print("Solvable")
        
    else:
        print("Not Solvable")
	

In [33]:
N= 3
S = get_state(N)
isSolvable(S)


[[6 0 7]
 [2 3 8]
 [4 1 5]]
[6, 0, 7, 2, 3, 8, 4, 1, 5]
3.0
3
17
Not Solvable
